[2022-09-14T13:10:43.166+0300] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: First-Dag.Compare_and_Print manual__2022-09-14T10:10:31.815339+00:00 [queued]>
[2022-09-14T13:10:43.177+0300] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: First-Dag.Compare_and_Print manual__2022-09-14T10:10:31.815339+00:00 [queued]>
[2022-09-14T13:10:43.177+0300] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-14T13:10:43.177+0300] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-14T13:10:43.177+0300] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-14T13:10:43.198+0300] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): Compare_and_Print> on 2022-09-14 10:10:31.815339+00:00
[2022-09-14T13:10:43.200+0300] {standard_task_runner.py:52} INFO - Started process 11625 to run task
[2022-09-14T13:10:43.203+0300] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'First-Dag', 'Compare_and_Print', 'manual__2022-09-14T10:10:31.815339+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/First_Dag.py', '--cfg-path', '/tmp/tmpus6nuzxt', '--error-file', '/tmp/tmp1so_6rqb']
[2022-09-14T13:10:43.204+0300] {standard_task_runner.py:80} INFO - Job 69: Subtask Compare_and_Print
[2022-09-14T13:10:43.255+0300] {task_command.py:371} INFO - Running <TaskInstance: First-Dag.Compare_and_Print manual__2022-09-14T10:10:31.815339+00:00 [running]> on host DESKTOP-6F0IB4Q.localdomain
[2022-09-14T13:10:43.316+0300] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=First-Dag
AIRFLOW_CTX_TASK_ID=Compare_and_Print
AIRFLOW_CTX_EXECUTION_DATE=2022-09-14T10:10:31.815339+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-14T10:10:31.815339+00:00
[2022-09-14T13:10:43.317+0300] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ragheed_ismail/Training-Project/test-project/.venv/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/ragheed_ismail/Training-Project/test-project/.venv/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ragheed_ismail/Training-Project/test-project/airflow_home/dags/First_Dag.py", line 17, in compare_and_print
    Array = ti.xcom_pull(keys='Numbers_Generated',task_ids=['RandomNumberGeneratorA','RandomNumberGeneratorB','RandomNumberGeneratorC'])
  File "/home/ragheed_ismail/Training-Project/test-project/.venv/lib/python3.8/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'keys'
[2022-09-14T13:10:43.321+0300] {taskinstance.py:1407} INFO - Marking task as FAILED. dag_id=First-Dag, task_id=Compare_and_Print, execution_date=20220914T101031, start_date=20220914T101043, end_date=20220914T101043
[2022-09-14T13:10:43.338+0300] {standard_task_runner.py:92} ERROR - Failed to execute job 69 for task Compare_and_Print (xcom_pull() got an unexpected keyword argument 'keys'; 11625)
[2022-09-14T13:10:43.375+0300] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-14T13:10:43.390+0300] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
