[2022-09-14T13:10:37.312+0300] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: First-Dag.RandomNumberGeneratorA manual__2022-09-14T10:10:31.815339+00:00 [queued]>
[2022-09-14T13:10:37.321+0300] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: First-Dag.RandomNumberGeneratorA manual__2022-09-14T10:10:31.815339+00:00 [queued]>
[2022-09-14T13:10:37.322+0300] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-14T13:10:37.322+0300] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-14T13:10:37.322+0300] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-14T13:10:37.342+0300] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): RandomNumberGeneratorA> on 2022-09-14 10:10:31.815339+00:00
[2022-09-14T13:10:37.344+0300] {standard_task_runner.py:52} INFO - Started process 11612 to run task
[2022-09-14T13:10:37.347+0300] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'First-Dag', 'RandomNumberGeneratorA', 'manual__2022-09-14T10:10:31.815339+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/First_Dag.py', '--cfg-path', '/tmp/tmp_9p30__5', '--error-file', '/tmp/tmp_fowmtty']
[2022-09-14T13:10:37.348+0300] {standard_task_runner.py:80} INFO - Job 65: Subtask RandomNumberGeneratorA
[2022-09-14T13:10:37.410+0300] {task_command.py:371} INFO - Running <TaskInstance: First-Dag.RandomNumberGeneratorA manual__2022-09-14T10:10:31.815339+00:00 [running]> on host DESKTOP-6F0IB4Q.localdomain
[2022-09-14T13:10:37.480+0300] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=First-Dag
AIRFLOW_CTX_TASK_ID=RandomNumberGeneratorA
AIRFLOW_CTX_EXECUTION_DATE=2022-09-14T10:10:31.815339+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-14T10:10:31.815339+00:00
[2022-09-14T13:10:37.481+0300] {python.py:173} INFO - Done. Returned value was: 4
[2022-09-14T13:10:37.504+0300] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=First-Dag, task_id=RandomNumberGeneratorA, execution_date=20220914T101031, start_date=20220914T101037, end_date=20220914T101037
[2022-09-14T13:10:37.559+0300] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-14T13:10:37.582+0300] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
